# Monte Carlo simulations

In [1]:
import numpy as np
import pandas as pd
import sys
import glob
import plotly.express as px
from pathlib import Path


project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

from src.utils import load_config
from src.monte_carlo import run_simulation_grid
from src.metrics import summarize_df
from src.figures import frontier_heatmap, estimator_metric_heatmap, frontier_panels, estimator_metric_panels

c:\Users\danil\anaconda3\envs\vcausal\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Running MC Sim

In [2]:
config = load_config("baseline")

df = run_simulation_grid(config, save_each=True, n_jobs=8)

alpha_y=0, alpha_d=0, kappa=0.5: 100%|██████████| 500/500 [01:38<00:00,  5.06it/s]
alpha_y=0, alpha_d=0, kappa=1: 100%|██████████| 500/500 [01:36<00:00,  5.18it/s]
alpha_y=0, alpha_d=0, kappa=2: 100%|██████████| 500/500 [01:35<00:00,  5.26it/s]
alpha_y=0, alpha_d=0.25, kappa=0.5: 100%|██████████| 500/500 [01:35<00:00,  5.25it/s]
alpha_y=0, alpha_d=0.25, kappa=1: 100%|██████████| 500/500 [01:45<00:00,  4.72it/s]
alpha_y=0, alpha_d=0.25, kappa=2: 100%|██████████| 500/500 [01:49<00:00,  4.56it/s]
alpha_y=0, alpha_d=0.5, kappa=0.5: 100%|██████████| 500/500 [01:53<00:00,  4.42it/s]
alpha_y=0, alpha_d=0.5, kappa=1: 100%|██████████| 500/500 [01:58<00:00,  4.22it/s]
alpha_y=0, alpha_d=0.5, kappa=2: 100%|██████████| 500/500 [01:58<00:00,  4.23it/s]
alpha_y=0, alpha_d=0.75, kappa=0.5: 100%|██████████| 500/500 [01:46<00:00,  4.68it/s]
alpha_y=0, alpha_d=0.75, kappa=1: 100%|██████████| 500/500 [01:56<00:00,  4.28it/s]
alpha_y=0, alpha_d=0.75, kappa=2: 100%|██████████| 500/500 [01:56<00:00,  4.30it/s]
alpha_y=0, alpha_d=1, kappa=0.5: 100%|██████████| 500/500 [01:36<00:00,  5.21it/s]
alpha_y=0, alpha_d=1, kappa=1: 100%|██████████| 500/500 [01:32<00:00,  5.39it/s]
alpha_y=0, alpha_d=1, kappa=2: 100%|██████████| 500/500 [01:36<00:00,  5.21it/s]
alpha_y=0.25, alpha_d=0, kappa=0.5: 100%|██████████| 500/500 [02:02<00:00,  4.08it/s]
alpha_y=0.25, alpha_d=0, kappa=1: 100%|██████████| 500/500 [01:45<00:00,  4.75it/s]
alpha_y=0.25, alpha_d=0, kappa=2: 100%|██████████| 500/500 [02:01<00:00,  4.11it/s]
alpha_y=0.25, alpha_d=0.25, kappa=0.5: 100%|██████████| 500/500 [01:52<00:00,  4.45it/s]
alpha_y=0.25, alpha_d=0.25, kappa=1: 100%|██████████| 500/500 [02:01<00:00,  4.12it/s]
alpha_y=0.25, alpha_d=0.25, kappa=2: 100%|██████████| 500/500 [01:52<00:00,  4.46it/s]
alpha_y=0.25, alpha_d=0.5, kappa=0.5: 100%|██████████| 500/500 [01:35<00:00,  5.25it/s]
alpha_y=0.25, alpha_d=0.5, kappa=1: 100%|██████████| 500/500 [01:39<00:00,  5.02it/s]
alpha_y=0.25, alpha_d=0.5, kappa=2: 100%|██████████| 500/500 [01:50<00:00,  4.52it/s]
alpha_y=0.25, alpha_d=0.75, kappa=0.5: 100%|██████████| 500/500 [01:35<00:00,  5.25it/s]
alpha_y=0.25, alpha_d=0.75, kappa=1: 100%|██████████| 500/500 [01:40<00:00,  4.98it/s]
alpha_y=0.25, alpha_d=0.75, kappa=2: 100%|██████████| 500/500 [01:59<00:00,  4.19it/s]
alpha_y=0.25, alpha_d=1, kappa=0.5: 100%|██████████| 500/500 [01:56<00:00,  4.29it/s]
alpha_y=0.25, alpha_d=1, kappa=1: 100%|██████████| 500/500 [01:53<00:00,  4.42it/s]
alpha_y=0.25, alpha_d=1, kappa=2: 100%|██████████| 500/500 [01:55<00:00,  4.31it/s]
alpha_y=0.5, alpha_d=0, kappa=0.5: 100%|██████████| 500/500 [01:59<00:00,  4.19it/s]
alpha_y=0.5, alpha_d=0, kappa=1: 100%|██████████| 500/500 [01:59<00:00,  4.18it/s]
alpha_y=0.5, alpha_d=0, kappa=2: 100%|██████████| 500/500 [02:01<00:00,  4.10it/s]
alpha_y=0.5, alpha_d=0.25, kappa=0.5: 100%|██████████| 500/500 [01:34<00:00,  5.31it/s]
alpha_y=0.5, alpha_d=0.25, kappa=1: 100%|██████████| 500/500 [01:34<00:00,  5.32it/s]
alpha_y=0.5, alpha_d=0.25, kappa=2: 100%|██████████| 500/500 [01:33<00:00,  5.33it/s]
alpha_y=0.5, alpha_d=0.5, kappa=0.5: 100%|██████████| 500/500 [01:35<00:00,  5.23it/s]
alpha_y=0.5, alpha_d=0.5, kappa=1: 100%|██████████| 500/500 [01:34<00:00,  5.32it/s]
alpha_y=0.5, alpha_d=0.5, kappa=2: 100%|██████████| 500/500 [01:31<00:00,  5.45it/s]
alpha_y=0.5, alpha_d=0.75, kappa=0.5: 100%|██████████| 500/500 [01:33<00:00,  5.32it/s]
alpha_y=0.5, alpha_d=0.75, kappa=1: 100%|██████████| 500/500 [01:36<00:00,  5.20it/s]
alpha_y=0.5, alpha_d=0.75, kappa=2: 100%|██████████| 500/500 [01:36<00:00,  5.19it/s]
alpha_y=0.5, alpha_d=1, kappa=0.5: 100%|██████████| 500/500 [01:34<00:00,  5.31it/s]
alpha_y=0.5, alpha_d=1, kappa=1: 100%|██████████| 500/500 [01:31<00:00,  5.45it/s]
alpha_y=0.5, alpha_d=1, kappa=2: 100%|██████████| 500/500 [01:33<00:00,  5.36it/s]
alpha_y=0.75, alpha_d=0, kappa=0.5: 100%|██████████| 500/500 [01:36<00:00,  5.16it/s]
alpha_y=0.75, alpha_d=0, kappa=1: 100%|██████████| 500/500 [01:35<00:00,  5.22it/s]
alpha_y=0.75, alpha_d=0, kappa=2: 100%|██████████| 500/500 [01:35<00:00,  5.25it/s]
alpha_y=0.75, alpha_d=0.25, kappa=0.5: 100%|██████████| 500/500 [01:37<00:00,  5.15it/s]
alpha_y=0.75, alpha_d=0.25, kappa=1: 100%|██████████| 500/500 [01:35<00:00,  5.24it/s]
alpha_y=0.75, alpha_d=0.25, kappa=2: 100%|██████████| 500/500 [01:34<00:00,  5.29it/s]
alpha_y=0.75, alpha_d=0.5, kappa=0.5: 100%|██████████| 500/500 [01:36<00:00,  5.20it/s]
alpha_y=0.75, alpha_d=0.5, kappa=1: 100%|██████████| 500/500 [01:35<00:00,  5.21it/s]
alpha_y=0.75, alpha_d=0.5, kappa=2: 100%|██████████| 500/500 [01:34<00:00,  5.28it/s]
alpha_y=0.75, alpha_d=0.75, kappa=0.5: 100%|██████████| 500/500 [01:34<00:00,  5.27it/s]
alpha_y=0.75, alpha_d=0.75, kappa=1: 100%|██████████| 500/500 [01:35<00:00,  5.26it/s]
alpha_y=0.75, alpha_d=0.75, kappa=2: 100%|██████████| 500/500 [01:36<00:00,  5.18it/s]
alpha_y=0.75, alpha_d=1, kappa=0.5: 100%|██████████| 500/500 [01:34<00:00,  5.29it/s]
alpha_y=0.75, alpha_d=1, kappa=1: 100%|██████████| 500/500 [01:35<00:00,  5.23it/s]
alpha_y=0.75, alpha_d=1, kappa=2: 100%|██████████| 500/500 [01:35<00:00,  5.26it/s]
alpha_y=1, alpha_d=0, kappa=0.5: 100%|██████████| 500/500 [01:35<00:00,  5.24it/s]
alpha_y=1, alpha_d=0, kappa=1: 100%|██████████| 500/500 [01:38<00:00,  5.07it/s]
alpha_y=1, alpha_d=0, kappa=2: 100%|██████████| 500/500 [01:35<00:00,  5.23it/s]
alpha_y=1, alpha_d=0.25, kappa=0.5: 100%|██████████| 500/500 [01:34<00:00,  5.26it/s]
alpha_y=1, alpha_d=0.25, kappa=1: 100%|██████████| 500/500 [01:36<00:00,  5.19it/s]
alpha_y=1, alpha_d=0.25, kappa=2: 100%|██████████| 500/500 [01:36<00:00,  5.20it/s]
alpha_y=1, alpha_d=0.5, kappa=0.5: 100%|██████████| 500/500 [01:36<00:00,  5.19it/s]
alpha_y=1, alpha_d=0.5, kappa=1: 100%|██████████| 500/500 [01:36<00:00,  5.20it/s]
alpha_y=1, alpha_d=0.5, kappa=2: 100%|██████████| 500/500 [01:34<00:00,  5.27it/s]
alpha_y=1, alpha_d=0.75, kappa=0.5: 100%|██████████| 500/500 [01:34<00:00,  5.28it/s]
alpha_y=1, alpha_d=0.75, kappa=1: 100%|██████████| 500/500 [01:39<00:00,  5.00it/s]
alpha_y=1, alpha_d=0.75, kappa=2: 100%|██████████| 500/500 [01:34<00:00,  5.27it/s]
alpha_y=1, alpha_d=1, kappa=0.5: 100%|██████████| 500/500 [01:36<00:00,  5.16it/s]
alpha_y=1, alpha_d=1, kappa=1: 100%|██████████| 500/500 [01:34<00:00,  5.29it/s]
alpha_y=1, alpha_d=1, kappa=2: 100%|██████████| 500/500 [01:36<00:00,  5.19it/s]

In [2]:
folder = Path().cwd() / "results" / "raw"

files = list(folder.glob("*.parquet"))


all_results = [pd.read_parquet(f) for f in files]
df = pd.concat(all_results, ignore_index=True)

In [10]:
df

,alpha_y,alpha_d,kappa,seed,replication,tau_true,ols_tau_hat,ols_se,ols_ci_lower,ols_ci_upper,dml_tau_hat,dml_se,dml_ci_lower,dml_ci_upper
0,0.25,0.25,0.5,42,0,2.5,2.371643,0.095408,2.184643,2.558644,2.449772,0.102224,2.249414,2.650131
1,0.25,0.25,0.5,43,1,2.5,2.608884,0.094026,2.424594,2.793174,2.669094,0.106497,2.460359,2.877828
2,0.25,0.25,0.5,44,2,2.5,2.651157,0.097307,2.460436,2.841879,2.608289,0.107842,2.396919,2.819660
3,0.25,0.25,0.5,45,3,2.5,2.529472,0.097213,2.338935,2.720009,2.544056,0.105458,2.337358,2.750754
4,0.25,0.25,0.5,46,4,2.5,2.555124,0.097280,2.364455,2.745794,2.564021,0.104488,2.359225,2.768818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37495,1.00,1.00,2.0,537,495,2.5,2.046252,0.198710,1.656780,2.435723,2.054218,0.133022,1.793495,2.314940
37496,1.00,1.00,2.0,538,496,2.5,2.487868,0.229676,2.037703,2.938032,2.194140,0.137284,1.925064,2.463217
37497,1.00,1.00,2.0,539,497,2.5,2.566798,0.151712,2.269442,2.864154,2.475612,0.139979,2.201254,2.749970
37498,1.00,1.00,2.0,540,498,2.5,2.713088,0.167299,2.385182,3.040994,2.472255,0.125018,2.227221,2.717289
37499,1.00,1.00,2.0,541,499,2.5,2.620681,0.190321,2.247652,2.993711,2.411422,0.134962,2.146898,2.675947

In [3]:
summary_df = summarize_df(df)
summary_df.head()

,estimator,bias,sd,rmse,coverage,avg_ci_length,alpha_y,alpha_d,kappa
0,OLS,-0.005495,0.097503,0.097560,0.936,0.367338,0.0,0.0,0.5
1,DML,0.009291,0.114778,0.115039,0.944,0.426882,0.0,0.0,0.5
2,OLS,-0.003479,0.104804,0.104757,0.938,0.391400,0.0,0.0,1.0
3,DML,-0.047974,0.124172,0.133001,0.908,0.453424,0.0,0.0,1.0
4,OLS,0.001120,0.125216,0.125095,0.926,0.448260,0.0,0.0,2.0

## Frontiers

In [9]:
fig = frontier_heatmap(summary_df, kappa=0.5)
fig.show()

In [5]:
fig = estimator_metric_heatmap(summary_df, metric="bias", estimator="OLS", kappa=1)
fig.show()

In [6]:
fig = estimator_metric_heatmap(summary_df, metric="bias", estimator="DML", kappa=1)
fig.show()

In [13]:
fig = estimator_metric_heatmap(summary_df, metric="sd", estimator="DML", kappa=1)
fig.show()

In [12]:
fig = estimator_metric_heatmap(summary_df, metric="sd", estimator="OLS", kappa=1)
fig.show()

In [15]:
fig = estimator_metric_heatmap(summary_df, metric="coverage", estimator="DML", kappa=1)
fig.show()

In [14]:
fig = estimator_metric_heatmap(summary_df, metric="coverage", estimator="OLS", kappa=1)
fig.show()

In [9]:
fig = frontier_panels(summary_df, kappas=[0.5, 1, 2.0])
fig.show()

In [4]:
fig = estimator_metric_panels(summary_df, metric="bias", estimator="OLS", kappas=[ 0.5, 1.0, 2])
fig.show()

In [5]:
fig = estimator_metric_panels(summary_df, metric="bias", estimator="DML", kappas=[ 0.5, 1.0, 2])
fig.show()

In [6]:
fig = estimator_metric_panels(summary_df, metric="sd", estimator="OLS", kappas=[ 0.5, 1.0, 2])
fig.show()

In [8]:
fig = estimator_metric_panels(summary_df, metric="sd", estimator="DML", kappas=[ 0.5, 1.0, 2])
fig.show()